### PR TITLE
Feature/adverts

### PR DESCRIPTION
**Pull request by lili2311**
Cause users can now create adverts and view them in their profile page.

### CODE REVIEW

**Comment by yanabar** [comment]
I'm trying to add a new ad and getting this:
image
I can't add my ad - maybe I need to create skills from admin site?

**Comment by yanabar** [comment]
I've created my ad from admin and everything looks okay !

**Comment by lili2311** [comment]
@yanabar skills is a model so you have to populate that first so you can choose form a selection of skills

**Comment by lili2311** [comment]
@yanabar are you happy with this PR or did you have any proposed changes?

**Pull request merged**
